// Generated by agent — 2026-06-02
import { useTheme } from "@/src/theme";
import { useState } from "react";
import {
  Text,
  View,
  StyleSheet,
  TouchableOpacity,
  ActivityIndicator,
  Image,
  Modal,
} from "react-native";
import { useAuth, useUser, useClerk } from "@clerk/expo";
import { AuthView, UserButton, UserProfileView } from "@clerk/expo/native";

export default function Profile() {
  const theme = useTheme();
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
      padding: 20,
      paddingTop: 60,
      gap: 16,
    },
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    title: { fontSize: 28, fontWeight: "bold", color: theme.foreground },
    button: {
      backgroundColor: theme.primary,
      padding: 16,
      borderRadius: 12,
      alignItems: "center",
    },
    buttonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  });

  const { isSignedIn, isLoaded } = useAuth({ treatPendingAsSignedOut: false });
  const { user } = useUser();
  const { signOut } = useClerk();
  const [isProfileVisible, setIsProfileVisible] = useState(false);

  if (!isLoaded) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" />
      </View>
    );
  }

  if (!isSignedIn) {
    return <AuthView mode="signInOrUp" />;
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Welcome</Text>
        <View
          style={{
            width: 44,
            height: 44,
            borderRadius: 22,
            overflow: "hidden",
          }}
        >
          <UserButton />
        </View>
      </View>
      {user?.imageUrl && (
        <Image
          source={{ uri: user.imageUrl }}
          style={{ width: 48, height: 48, borderRadius: 24 }}
        />
      )}
      <Text style={{ color: theme.foreground }}>
        {user?.fullName ?? user?.id}
      </Text>
      <TouchableOpacity
        style={styles.button}
        onPress={() => setIsProfileVisible(true)}
      >
        <Text style={styles.buttonText}>Manage Profile</Text>
      </TouchableOpacity>
      <TouchableOpacity style={styles.button} onPress={() => signOut()}>
        <Text style={styles.buttonText}>Sign Out</Text>
      </TouchableOpacity>
      <Modal
        visible={isProfileVisible}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setIsProfileVisible(false)}
      >
        <UserProfileView
          style={{ flex: 1 }}
          onDismiss={() => setIsProfileVisible(false)}
        />
      </Modal>
    </View>
  );
}
