// Generated by agent — 2026-05-15
import '@/src/global.css';

import { NAV_THEME } from '@/lib/theme';
import { PortalHost } from '@rn-primitives/portal';
import { ThemeProvider } from '@react-navigation/native';
import { Stack } from 'expo-router';
import { useColorScheme, Platform } from 'react-native';

export default function RootLayout() {
  const colorScheme = useColorScheme() ?? 'light';
  return (
    <ThemeProvider value={NAV_THEME[colorScheme]}>
      <Stack screenOptions={{ headerShown: Platform.OS !== 'web' }} />
      <PortalHost />
    </ThemeProvider>
  );
}
