// Generated by agent — 2026-06-04
import { useContext } from "react";
import { Text, View, TextInput, Pressable, Alert, Image } from "react-native";
import * as Calendar from "expo-calendar";
import { router } from "expo-router";
import { EventDraftContext } from "@/src/components/eventDraft";
import { DateField } from "@/src/components/DateField";

async function addToCalendar(
  name: string,
  starts_at: string,
  ends_at: string | null,
  location: string | null,
) {
  // Ask for permission to access the device calendar
  const { status } = await Calendar.requestCalendarPermissionsAsync();
  if (status !== "granted") {
    Alert.alert("Permission denied", "Calendar access is required.");
    return false;
  }

  // getDefaultCalendarSync() returns the calendar iOS considers the user's default
  const defaultCalendar = await Calendar.getDefaultCalendarAsync();

  await Calendar.createEventAsync(defaultCalendar.id, {
    title: name,
    startDate: new Date(starts_at),
    // Fall back to 1 hour after start if no end time provided
    endDate: new Date(ends_at ?? new Date(starts_at).setHours(new Date(starts_at).getHours() + 1)),
    location: location ?? undefined,
    timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  });

  return true;
}

export default function ConfirmModal() {
  // ! asserts the context is non-null (safe because EventDraftProvider wraps the whole app)
  const { eventDraft, setEventDraft, imageUri } = useContext(EventDraftContext)!;

  if (!eventDraft) {
    return (
      <View className="centered-full">
        <Text>No event to confirm.</Text>
      </View>
    );
  }

  const inputClass = "border border-gray-300 rounded-lg p-3";

  return (
    <View className="flex-1 p-6 gap-6">
      {/* Human-readable summary from the agent — capped to avoid dominating the screen */}
      <Text className="text-gray-500" numberOfLines={3}>{eventDraft.user_facing_context}</Text>

      <TextInput
        placeholder="Name"
        value={eventDraft.name}
        // Spread the existing draft and overwrite just the changed field
        onChangeText={(name) => setEventDraft({ ...eventDraft, name })}
        className={inputClass}
      />

      <DateField
        value={eventDraft.starts_at}
        onChange={(starts_at) => setEventDraft({ ...eventDraft, starts_at })}
      />
      {/* Fall back to starts_at as the initial value if ends_at is null */}
      <DateField
        value={eventDraft.ends_at ?? eventDraft.starts_at}
        onChange={(ends_at) => setEventDraft({ ...eventDraft, ends_at })}
      />

      <TextInput
        placeholder="Location"
        value={eventDraft.location ?? ""}
        onChangeText={(location) => setEventDraft({ ...eventDraft, location })}
        className={inputClass}
      />

      {/* mt-auto pushes the button to the bottom of the screen */}
      <Pressable
        className="bg-blue-500 rounded-xl p-4 items-center mt-auto"
        onPress={async () => {
          const success = await addToCalendar(
            eventDraft.name,
            eventDraft.starts_at,
            eventDraft.ends_at,
            eventDraft.location,
          );
          if (success) {
            setEventDraft(null); // clear the draft
            router.back();       // dismiss the modal
          }
        }}
      >
        <Text className="text-white font-semibold">Add to Calendar</Text>
      </Pressable>
      {imageUri && <Image source={{ uri: imageUri }} style={{ height: 200, borderRadius: 8 }} resizeMode="cover" />}
    </View>
  );
}
