// Generated by agent — 2026-06-04
import { useContext } from "react";
import { Text, View, TextInput, Pressable } from "react-native";
import { EventDraftContext } from "@/src/components/eventDraft";
import { DateField } from "@/src/components/DateField";

export default function ConfirmModal() {
  // ! asserts the context is non-null (safe because EventDraftProvider wraps the whole app)
  const { eventDraft, setEventDraft } = useContext(EventDraftContext)!;

  // Early return if no image has been processed yet
  if (!eventDraft) {
    return (
      <View className="flex-1 items-center justify-center">
        <Text>No event to confirm.</Text>
      </View>
    );
  }

  const inputClass = "border border-gray-300 rounded-lg p-3";

  return (
    <View className="flex-1 p-6 gap-6">
      {/* Human-readable summary from the agent — capped to avoid dominating the screen */}
      <Text className="text-gray-500" numberOfLines={3}>{eventDraft.user_facing_context}</Text>

      <TextInput
        placeholder="Name"
        value={eventDraft.name}
        // Spread the existing draft and overwrite just the changed field
        onChangeText={(name) => setEventDraft({ ...eventDraft, name })}
        className={inputClass}
      />

      <DateField
        value={eventDraft.starts_at}
        onChange={(starts_at) => setEventDraft({ ...eventDraft, starts_at })}
      />
      {/* Fall back to starts_at as the initial value if ends_at is null */}
      <DateField
        value={eventDraft.ends_at ?? eventDraft.starts_at}
        onChange={(ends_at) => setEventDraft({ ...eventDraft, ends_at })}
      />

      <TextInput
        placeholder="Location"
        value={eventDraft.location ?? ""}
        onChangeText={(location) => setEventDraft({ ...eventDraft, location })}
        className={inputClass}
      />

      {/* TODO: call POST /api/events with EventSafeCreateSchema.parse(eventDraft) */}
      {/* mt-auto pushes the button to the bottom of the screen */}
      <Pressable className="bg-blue-500 rounded-xl p-4 items-center mt-auto">
        <Text className="text-white font-semibold">Add to Calendar</Text>
      </Pressable>
    </View>
  );
}
