// Partially generated by agent — 2026-06-15 (calendar logic, multi-event loop, workarounds)
import { useContext } from "react";
import { Text, View, TextInput, Pressable, Alert, Image, ScrollView } from "react-native";
import * as Calendar from "expo-calendar";
import { router } from "expo-router";
import { EventDraft, EventDraftContext } from "@/src/components/eventDraft";
import { DateField } from "@/src/components/DateField";

const frequencyMap: Record<string, Calendar.Frequency> = {
  daily: Calendar.Frequency.DAILY,
  weekly: Calendar.Frequency.WEEKLY,
  monthly: Calendar.Frequency.MONTHLY,
  yearly: Calendar.Frequency.YEARLY,
};

// Shifts a date forward to the next occurrence of a given day of week (0=Sun…6=Sat)
function nextOccurrenceOfDay(from: Date, targetDay: number): Date {
  const result = new Date(from);
  const diff = (targetDay - result.getDay() + 7) % 7;
  result.setDate(result.getDate() + diff);
  return result;
}

async function addAllToCalendar(drafts: EventDraft[]) {
  // Ask for permission to access the device calendar
  const { status } = await Calendar.requestCalendarPermissionsAsync();
  if (status !== "granted") {
    Alert.alert("Permission denied", "Calendar access is required.");
    return false;
  }

  // getDefaultCalendarAsync() returns the calendar iOS considers the user's default
  const defaultCalendar = await Calendar.getDefaultCalendarAsync();

  for (const draft of drafts) {
    const start = new Date(draft.starts_at);
    // Fall back to 1 hour after start if no end time provided
    // Duration in ms so we can compute the correct end time after shifting start to a new day
    const durationMs = draft.ends_at
      ? new Date(draft.ends_at).getTime() - start.getTime()
      : 60 * 60 * 1000; // default 1 hour

    // daysOfTheWeek is broken in expo-calendar's iOS native bridge (PR #36482).
    // Workaround: for multi-day recurrence (e.g. every Wed + Thu), create one
    // weekly event per day, each starting on its first occurrence. A weekly event
    // starting on a Wednesday will always recur on Wednesdays.
    const days = draft.recurrence?.days_of_week?.length ? draft.recurrence.days_of_week : [null];

    for (const day of days) {
      const eventStart = day !== null ? nextOccurrenceOfDay(start, day) : start;
      const eventEnd = new Date(eventStart.getTime() + durationMs);

      await Calendar.createEventAsync(defaultCalendar.id, {
        title: draft.name,
        startDate: eventStart,
        endDate: eventEnd,
        location: draft.location ?? undefined,
        notes: [draft.notes, "Added by Smartpage"].filter(Boolean).join("\n\n"),
        url: draft.url ?? undefined,
        timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        recurrenceRule: draft.recurrence ? {
          frequency: frequencyMap[draft.recurrence.frequency],
          interval: draft.recurrence.interval,
          endDate: draft.recurrence.end_date ? new Date(draft.recurrence.end_date) : undefined,
        } : undefined,
      });
    }
  }
  return true;
}

export default function ConfirmModal() {
  // ! asserts the context is non-null (safe because EventDraftProvider wraps the whole app)
  const { eventDrafts, setEventDrafts, imageUri } = useContext(EventDraftContext)!;

  if (!eventDrafts.length) {
    return (
      <View className="centered-full">
        <Text>No event to confirm.</Text>
      </View>
    );
  }

  // Overwrite one draft at index i, keeping the rest unchanged
  const updateDraft = (i: number, updated: EventDraft) =>
    setEventDrafts(eventDrafts.map((d, j) => (j === i ? updated : d)));

  const inputClass = "border border-gray-300 rounded-lg p-3";

  return (
    <View className="flex-1">
      {/* ScrollView unlike View allows children to overflow the screen height and be scrolled to */}
      <ScrollView className="flex-1 p-6" contentContainerStyle={{ gap: 24 }}>
        {imageUri && (
          <Image source={{ uri: imageUri }} style={{ height: 200, borderRadius: 8 }} resizeMode="cover" />
        )}

        {eventDrafts.map((draft, i) => (
          <View key={i} className="gap-4">
            {/* Divider between events when there are multiple */}
            {i > 0 && <View className="border-t border-gray-200" />}

            {/* Human-readable summary from the agent — capped to avoid dominating the screen */}
            <Text className="text-gray-500" numberOfLines={3}>
              {draft.user_facing_context}
            </Text>

            <TextInput
              placeholder="Name"
              value={draft.name}
              // Spread the existing draft and overwrite just the changed field
              onChangeText={(name) => updateDraft(i, { ...draft, name })}
              className={inputClass}
            />

            <DateField
              value={draft.starts_at}
              onChange={(starts_at) => updateDraft(i, { ...draft, starts_at })}
            />
            {/* Fall back to starts_at as the initial value if ends_at is null */}
            <DateField
              value={draft.ends_at ?? draft.starts_at}
              onChange={(ends_at) => updateDraft(i, { ...draft, ends_at })}
            />

            {draft.recurrence && (
              // Read-only — recurrence editing not yet supported
              <Text className="text-gray-500 text-sm">
                🔁 Every {draft.recurrence.interval > 1 ? `${draft.recurrence.interval} ` : ""}{draft.recurrence.frequency}
                {draft.recurrence.end_date ? ` until ${new Date(draft.recurrence.end_date).toLocaleDateString()}` : ""}
              </Text>
            )}

            <TextInput
              placeholder="Location"
              value={draft.location ?? ""}
              onChangeText={(location) => updateDraft(i, { ...draft, location })}
              className={inputClass}
            />
          </View>
        ))}
      </ScrollView>

      {/* mt-auto pushes the button to the bottom of the screen */}
      <Pressable
        className="bg-blue-500 rounded-xl p-4 items-center mx-6 mb-8"
        onPress={async () => {
          const success = await addAllToCalendar(eventDrafts);
          if (success) {
            setEventDrafts([]);
            router.back();
          }
        }}
      >
        <Text className="text-white font-semibold">Add to Calendar</Text>
      </Pressable>
    </View>
  );
}
