#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["Pillow"]
# ///
# Generated by agent — 2026-06-15
# Generates a fake paper-calendar PNG with multiple events (including a recurring one)
# to test multi-event + recurrence extraction.
# Usage: ./gen-test-calendar.py [-o OUTPUT]

import argparse
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

FONT_CANDIDATES = [
    "/System/Library/Fonts/Supplemental/Georgia.ttf",
    "/Library/Fonts/Georgia.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
    "C:/Windows/Fonts/georgia.ttf",
]

def find_font():
    for p in FONT_CANDIDATES:
        if Path(p).exists():
            return p
    return None

def load(size):
    base = find_font()
    if base is None:
        return ImageFont.load_default()
    try:
        return ImageFont.truetype(base, size)
    except Exception:
        return ImageFont.load_default()

WIDTH, HEIGHT = 600, 820
BG     = (255, 252, 240)   # warm off-white (looks like paper)
FG     = (30,  30,  30)
ACCENT = (180, 60,  60)
LINE   = (200, 190, 170)
GRAY   = (120, 120, 120)

def build(output: str):
    img  = Image.new("RGB", (WIDTH, HEIGHT), BG)
    draw = ImageDraw.Draw(img)

    font_title = load(28)
    font_body  = load(18)
    font_small = load(14)

    # Header bar
    draw.rectangle([(0, 0), (WIDTH, 70)], fill=ACCENT)
    draw.text((20, 18), "JUNE / JULY 2026", font=font_title, fill=(255, 255, 255))

    y = 90

    def section(title, lines, tag=None):
        nonlocal y
        draw.line([(20, y), (WIDTH - 20, y)], fill=LINE, width=1)
        y += 10
        draw.text((20, y), title, font=font_body, fill=ACCENT)
        if tag:
            tw = int(draw.textlength(tag, font=font_small))
            draw.text((WIDTH - 20 - tw, y + 2), tag, font=font_small, fill=GRAY)
        y += 28
        for line in lines:
            draw.text((30, y), line, font=font_small, fill=FG)
            y += 22
        y += 10

    section(
        "Neon Harbor: Farewell Tour",
        [
            "Date:     Sunday, June 14, 2026",
            "Time:     Doors 7:00 PM · Show 9:00 PM",
            "Venue:    The Marquee, 1247 N Phantom Ave, Chicago IL",
            "Tickets:  $35 / $55 / $90  ·  All ages",
            "URL:      neonharbor.example.com",
        ],
    )

    section(
        "Pottery with Maria",
        [
            "Every Wednesday & Thursday, 6:00 PM – 8:00 PM",
            "Starting June 18 · Ends August 28, 2026",
            "Location: Clayworks Studio, 409 W Elm St",
            "Notes:    Bring apron. Beginners welcome.",
        ],
        tag="RECURRING",
    )

    section(
        "Chicago Tech Meetup",
        [
            "Date:     Tuesday, July 7, 2026",
            "Time:     6:30 PM – 9:00 PM",
            "Location: 1871 Chicago, 222 W Merchandise Mart Plaza",
            "Notes:    Free admission. RSVP at chicagotech.example.com",
        ],
    )

    section(
        "Dad's Birthday Dinner",
        [
            "Date:     Saturday, July 18, 2026",
            "Time:     7:00 PM",
            "Location: Osteria Via Stato, 620 N State St, Chicago",
        ],
    )

    img.save(output, "PNG")
    print(f"✓ {output}  (4 events, 1 recurring)")

def main():
    p = argparse.ArgumentParser(description="Generate a multi-event calendar PNG for agent testing.")
    p.add_argument("-o", "--output", default="test-calendar.png", help="Output path (default: test-calendar.png)")
    args = p.parse_args()
    build(args.output)

if __name__ == "__main__":
    main()
