// Generated by agent — 2026-06-04
import { useState } from "react";
import { Text, Pressable, View } from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { borderRadius, colors } from "@/src/theme";

// iOS modal sheets always render with a light background regardless of system dark mode,
// so we hardcode light theme colors here rather than reading from useColorScheme()
const theme = colors.light;

export function DateField({
  value,
  onChange,
}: {
  value: string;
  onChange: (iso: string) => void;
}) {
  const [visible, setVisible] = useState(false);

  return (
    <View>
      {/* Tapping toggles the inline picker */}
      <Pressable
        onPress={() => setVisible((v) => !v)}
        style={{
          borderColor: theme.foreground,
          borderWidth: 1,
          borderRadius: borderRadius,
          padding: 12,
        }}
      >
        <Text style={{ color: theme.foreground }}>
          {new Date(value).toLocaleString()}
        </Text>
      </Pressable>
      {visible && (
        // display="inline" renders in-place — avoids modal-in-modal conflict on iOS
        <DateTimePicker
          mode="datetime"
          display="inline"
          value={new Date(value)}
          themeVariant="light"
          accentColor={theme.primary}
          onChange={(_, date) => {
            // toISOString() converts back to ISO string for storage
            if (date) onChange(date.toISOString());
          }}
        />
      )}
    </View>
  );
}
