// (Originally) generated by agent — 2026-06-04
import { AppType } from "api";
import { hc, InferResponseType } from "hono/client";
import { createContext, useState } from "react";

// Walk the Hono client type tree to the $post function, then extract its 200 response shape
type ProcessResponse = InferResponseType<
  ReturnType<typeof hc<AppType>>["api"]["events"]["process"]["$post"],
  200
>;
// The draft is just the eventDetails field from that response
export type EventDraft = ProcessResponse["eventDetails"]

type EventDraftContextType = {
  eventDraft: EventDraft | null;
  // Dispatch<SetStateAction> accepts both a value and an updater function (prev => next)
  setEventDraft: React.Dispatch<React.SetStateAction<EventDraft | null>>;
  imageUri: string | null;
  setImageUri: React.Dispatch<React.SetStateAction<string | null>>;

};

export const EventDraftContext = createContext<EventDraftContextType | null>(
  null,
);

export function EventDraftProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [eventDraft, setEventDraft] = useState<EventDraft | null>(null);
  const [imageUri, setImageUri] = useState<string | null>(null);
  return (
    <EventDraftContext value={{ eventDraft, setEventDraft, setImageUri, imageUri}}>
      {children}
    </EventDraftContext>
  );
}
