// (Originally) generated by agent — 2026-06-04
import { AppType } from "api";
import { hc, InferResponseType } from "hono/client";
import { createContext, useState } from "react";

// Walk the Hono client type tree to the $post function, then extract its 200 response shape
type ProcessResponse = InferResponseType<
  ReturnType<typeof hc<AppType>>["api"]["events"]["process"]["$post"],
  200
>;
// A single event from the array the agent returns
export type EventDraft = ProcessResponse["eventDetails"]["events"][number];

type EventDraftContextType = {
  // Array of events extracted from the image
  eventDrafts: EventDraft[];
  setEventDrafts: React.Dispatch<React.SetStateAction<EventDraft[]>>;
  imageUri: string | null;
  setImageUri: React.Dispatch<React.SetStateAction<string | null>>;
};

export const EventDraftContext = createContext<EventDraftContextType | null>(
  null,
);

export function EventDraftProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [eventDrafts, setEventDrafts] = useState<EventDraft[]>([]);
  const [imageUri, setImageUri] = useState<string | null>(null);
  return (
    <EventDraftContext
      value={{ eventDrafts, setEventDrafts, setImageUri, imageUri }}
    >
      {children}
    </EventDraftContext>
  );
}
