// Generated by agent — 2026-06-06
// Extends app.json with runtime env vars. The function form receives app.json
// as `config` so we only need to override what changes — everything else inherits.

import { ConfigContext, ExpoConfig } from "expo/config";

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...(config as ExpoConfig),
  // APP_VERSION is set by CI to <major.minor>.<run_number> so CFBundleShortVersionString
  // increments on every build and SideStore detects updates. Falls back to app.json locally.
  ...(process.env.APP_VERSION ? { version: process.env.APP_VERSION } : {}),
  extra: {
    ...config.extra,
    // Comma-separated URLs tried in order — first reachable one wins.
    // Set BACKEND_URLS in .env (local) or GitHub Actions secrets (CI).
    backendUrls: process.env.BACKEND_URLS?.split(",") ?? [
      "http://localhost:3000",
    ],
  },
});
