#!/bin/sh
# Generated by agent — 2026-06-06
# Builds an unsigned .ipa in dist/ for sideloading via SideStore.
# SideStore re-signs with your Apple ID on install — no Apple Developer account needed here.
# Usage: sh build-sideload.sh

set -e

# expo.name in app.json matches the Xcode scheme name for all expo prebuild projects
APP_NAME=smartpage  # must match expo.name in app.json and the Xcode scheme

echo "Building unsigned IPA for: $APP_NAME"

# --clean wipes ios/ entirely and regenerates — ensures no stale pod paths or native config
CI=1 bunx expo prebuild --platform ios --clean

# Resolve Swift Package transitive dependencies (Nuke, PhoneNumberKit, etc.) before compiling
xcodebuild -resolvePackageDependencies \
  -workspace "ios/$APP_NAME.xcworkspace" \
  -scheme "$APP_NAME"

# Archive without signing — CODE_SIGN_IDENTITY="" skips certificate lookup entirely
xcodebuild archive \
  -workspace "ios/$APP_NAME.xcworkspace" \
  -scheme "$APP_NAME" \
  -configuration Release \
  -archivePath "build/$APP_NAME.xcarchive" \
  CODE_SIGNING_ALLOWED=NO \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGN_IDENTITY=""

# An IPA is just a zip of Payload/<App>.app — no xcodebuild -exportArchive needed
rm -rf dist
mkdir -p dist/Payload
cp -R "build/$APP_NAME.xcarchive/Products/Applications/$APP_NAME.app" "dist/Payload/$APP_NAME.app"
cd dist && zip -r "$APP_NAME.ipa" Payload && rm -rf Payload

echo ""
echo "Done: packages/app/dist/$APP_NAME.ipa"
echo "Import this file into SideStore to install."
