// Generated by agent — 2026-05-15
// cn() merges Tailwind classes safely — clsx handles conditionals,
// twMerge resolves conflicts (e.g. "p-2 p-4" → "p-4")
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
