// Generated by agent — 2026-06-08
import * as z from "zod";

export const DbUserSchema = z.object({
  id: z.string().uuid(),
  clerk_id: z.string(),
  created_at: z.date(),
});

export type DbUser = z.infer<typeof DbUserSchema>;
