import { del, issueSignedToken, list, presignUrl } from '@vercel/blob';
import { sign } from 'hono/jwt'
import { UploadJwtPayload } from './types/misc';

export const JWT_SECRET = process.env.AI_GATEWAY_API_KEY as string;
const JWT_EXPIRATION = 60 * 60; // 1 hour in seconds
const PREFIX = 'for-processing';
const days_to_keep = 2;

export async function getPresignedImageUploadUrl(path: string): Promise<{ presignedUrl: string }> {
const today = new Date();
const token = await issueSignedToken({
  operations: ['put'],
  pathname: path,
  allowedContentTypes: ['image/png', 'image/jpg', 'image/jpeg'],
  maximumSizeInBytes: 10 * 1024 * 1024, // 10 MB
  validUntil: Date.now() + 60 * 60 * 1000, // 1 hour from now
})

const { presignedUrl } = await presignUrl(token, {
  operation: 'put',
  access: 'private',
  pathname: path,
  addRandomSuffix: false,
});

return { presignedUrl };
}

export const generateBlobPath = (userId: string, imageFormat: string): string => {
    const today = new Date(); 
    // padtStart froces each component to be 2 digits by adding a 0 to the left if necessary
    // path example: for-processing/userId/2023/09/15/b7f3d3ff-9b63-4551-9add-5260d510fdf0.jpeg
    return `${PREFIX}/${userId}/${today.getFullYear()}/${(today.getMonth() + 1).toString().padStart(2, '0')}/${today.getDate().toString().padStart(2, '0')}/${crypto.randomUUID()}.${imageFormat}`; 
}

export async function getJwtToken(path: string, userId: string, secret: string, expiresIn: number = JWT_EXPIRATION): Promise<string> {
  const payload: UploadJwtPayload = {
    sub: userId,
    exp: Math.floor(Date.now() / 1000) + expiresIn,
    uploadPath: path,
  };
  return await sign(payload, secret);
}


async function deleteOldFiles(days: number = days_to_keep) {
  const cutoff = Date.now() - days * 24 * 60 * 60 * 1000;
  let cursor: string | undefined;
  do {
    const res = await list({ prefix: `${PREFIX}/`, cursor });
    const stale = res.blobs.filter((b) => new Date(b.uploadedAt).getTime() < cutoff);
    if (stale.length) await del(stale.map((b) => b.url));
    // If there are more files to list, set the cursor for the next iteration
    // doesn't matter what the cursor is, it's generated by the API and is opaque, but passing it back will provide the next page of results
    cursor = res.hasMore ? res.cursor : undefined;
  } while (cursor);
}

